config/routes.rb
Rails.application.routes.draw do
  get 'movies/show'
  get 'movies/index'
  get 'bookmarks/new'
  get 'list/index'
  get 'list/show'
  get 'list/edit'
  get 'list/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :lists do
    resources :bookmarks, only: [:new]
  end
  resources :bookmarks, only: [:create, :destroy]


  resources :movies, only: [:show, :index]

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie, presence: true
  validates :list, presence: true
  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list, message: "This movie is already bookmarked in this list." }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :lists
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
     puts "Create action called"
    @movie = Movie.find(params[:movie_id])
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(movie: @movie, list: @list, comment: params[:comment])

    if @bookmark.save
      redirect_to list_path(@list), notice: "Film ajouté à la liste avec succès !"
    else
      alert("Le commentaire doit contenir au moins 6 caractères.")
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update]
  def index
    @lists = List.all
    @movies = Movie.all
  end

  def show
    @lists = List.all
    @bookmarks = Bookmark.where(list_id: @list)
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save

      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @list.update(list_params)
    redirect_to list_path(@list)
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def show
    @lists = List.all
    @movie = Movie.find(params[:id])
    @related_movies = Movie.order("RANDOM()").limit(10)
  end

  def index
    @movies = Movie.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="col-6 m-auto p-5">
  <div class="flat-form">
    <h1>Add movie to list</h1>
    <div class="mt-3">
      <%= simple_form_for([@list, @bookmark]) do |f| %>
        <%= f.input :comment, input_html: { class: 'form-control' }, label_html: { class: 'form-label' } %>
        <%= f.input :movie_id, collection: Movie.all, prompt: "Choose a movie", label: "Movie" %>
        <%= f.button :submit, "Add movie", class: 'btn btn-primary mt-3' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <%= yield %>

  </div>


  </body>
</html>

app/views/lists/edit.html.erb
<h1>List#edit</h1>
<p>Find me in app/views/list/edit.html.erb</p>

app/views/lists/index.html.erb
<div class="d-flex">
  <%= render 'shared/sidebar', lists: @lists %>
  <div class="container py-5">


    <div class="row">
      <div class="col">
        <p>All <%= @movies.count %> lists.</p>
      </div>
    </div>

    <div class="row">
  <% @movies.each do |movie| %>
    <div class="col-md-4 mb-4">
      <%= link_to movie_path(movie) do %>
        <div class="movie-card position-relative">
          <button class="bookmark-icon" data-bs-toggle="modal" data-bs-target="#selectListModal" data-movie-id="<%= movie.id %>">
            <i class="fas fa-bookmark"></i>
          </button>
          <img class="card-img-top" src="<%= movie.poster_url %>" alt="<%= movie.title %> poster">
          <div class="flat-card-content">
            <div class="card-title">
              <h4><%= movie.title %></h4>
            </div>
          </div>
          <div class="flat-card-actions">
            <%= link_to "More info", movie_path(movie), class: "movie-info-button" %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
  </div>
</div>
<%= render 'shared/add_to_list_modal', lists: @lists %>

app/views/lists/new.html.erb
<div class="col-6 m-auto p-5 ">
  <div class="flat-form p-5">
    <h1>Create new list</h1>
    <div class="mt-3">
      <%= simple_form_for(@list) do |f| %>
        <%= f.input :name, input_html: { class: 'form-control' }, label_html: { class: 'form-label' } %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, "Create list", class: 'btn btn-primary mt-3' %>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="d-flex ">
  <%= render 'shared/sidebar', lists: @lists %>
  <div class="container">
    <div class="movie-header" style="background-image: url('<%= cl_image_path @list.photo.key%>'); background-size: cover; height: 60vh; background-position: center;">
    <div class="overlay"></div>
      <div class="movie-info">
          <%= link_to request.referer || lists_path, class: "btn-back" do %>
            <i class="fas fa-arrow-left "></i>
          <% end %>
          <h1 class="movie-title"><%= @list.name %></h1>
          <div class="movie-actions">
              <%= link_to "Delete My List", "#", class: "btn btn-secondary" %>
          </div>
      </div>
      <div class="movie-thumbnail">
        <img src="<%= cl_image_path @list.photo.key%>" alt="<%= @list.name %>">
      </div>
  </div>
  <div class="row">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="col-md-4 mb-4">
        <%= link_to movie_path(bookmark.movie) do %>
          <div class="movie-card position-relative">
            <img class="card-img-top" src="<%= bookmark.movie.poster_url %>">
            <div class="flat-card-content">
              <div class="card-title">
                <h4><%= bookmark.movie.title %></h4>
              </div>
            </div>
            <div class="flat-card-actions">
              <%= link_to "Remove", bookmark_path(bookmark), class: "ms-3 text-danger", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

</div>
</div>

app/views/movies/index.html.erb
<h1>Movies#index</h1>
<p>Find me in app/views/movies/index.html.erb</p>

app/views/movies/show.html.erb
<div class="d-flex ">
  <%= render 'shared/sidebar', lists: @lists %>
  <div class="container">
    <div class="movie-header" style="background-image: url('<%= @movie.poster_url %>'); background-size: cover; height: 60vh; background-position: center;">
    <div class="overlay"></div>
      <div class="movie-info">
          <%= link_to request.referer || lists_path, class: "btn-back" do %>
            <i class="fas fa-arrow-left "></i>
          <% end %>
          <h1 class="movie-title"><%= @movie.title %></h1>
          <div class="d-flex stars">
            <i class="fas fa-star"></i>
            <p><%= @movie.rating.floor(1) %> / 10</p>
          </div>
          <p class="movie-description"><%= @movie.overview %></p>
          <div class="movie-actions">
              <%= link_to "#",
                  class: "btn btn-secondary",
                  data: {
                    bs_toggle: "modal",
                    bs_target: "#selectListModal",
                    movie_id: @movie.id
                  } do %>
                <div>Add to My List</div>
              <% end %>
              <%= link_to "Play", "#", class: "btn btn-primary" %>
          </div>
      </div>
      <div class="movie-thumbnail">
        <img src="<%= @movie.poster_url %>" alt="<%= @movie.title %>">
      </div>
  </div>
  <div class="related-movies mt-5">
    <h2>Related Movies</h2>
    <div class="carousel gap-4">
      <% @related_movies.each do |movie| %>
          <div class="col-md-3">
          <%= link_to movie_path(movie) do %>
              <div class="movie-card position-relative">
                  <img class="card-img-top" src= <%= movie.poster_url %>>
                  <div class="flat-card-content px-4">
                      <div class="card-title">
                          <h4 class="py-2"><%= movie.title %></h4>
                      </div>
                </div>
              </div>
              <% end %>
            </div>
      <% end %>

    </div>
  </div>
</div>
</div>
<%= render 'shared/add_to_list_modal', lists: @lists %>

app/views/shared/_add_to_list_modal.html.erb
<div class="modal fade" id="selectListModal" tabindex="-1" role="dialog" aria-labelledby="selectListModalLabel" aria-hidden="true" data-controller="bookmarks">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="selectListModalLabel">Select a List</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">&times;</button>
      </div>
      <div class="modal-body">
        <%= form_with url: bookmarks_path, method: :post, data: { turbo: true } do |f| %>
          <%= f.hidden_field :movie_id, id: "modal_movie_id" %>
          <div class="mb-3">
            <label for="list_id">Choose a List</label>
            <% lists.each do |list| %>
              <div class="form-check">
                <%= f.radio_button :list_id, list.id, data: { bookmarks_target: "radio", action: "input->bookmarks#updateSubmitButtonState" }, class: "form-check-input" %>
                <%= f.label :list_id, list.name, class: "form-check-label" %>
              </div>
            <% end %>
          </div>
          <div class="mb-3">
            <%= f.label :comment, "Comment", class: "form-label" %>
            <%= f.text_area :comment, required: true, class: "form-control", placeholder: "Add a comment...", data: { bookmarks_target: "comment", action: "input->bookmarks#updateSubmitButtonState" } %>
          </div>

          <%= f.submit "Add to List", class: "btn btn-primary", data: { bookmarks_target: "submitButton" }, disabled: true %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="sidebar d-flex flex-column p-3 vh-100">

  <a href="/" class="d-flex align-items-center mb-3 text-decoration-none">
    <svg class="bi me-2" width="40" height="32">
      <use xlink:href="#bootstrap" />
    </svg>
    <%= link_to lists_path, class: "text-decoration-none" do %>
      <%= image_tag "logo.png", alt: "tadam", width: 150 %>
    <% end %>
  </a>

  <hr />


  <ul class="nav flex-column mb-auto">
    <li class="nav-item">
      <%= link_to new_list_path do %>
        <button class="btn btn-primary">Create new list</button>
      <% end %>
    </li>
    <hr>
    <li><p>Your WatchLists</p></li>
    <% lists.each do |list| %>
      <li class="nav-item">
        <%= link_to list_path(list), class: "nav-link" do %>
          <% if list.photo.attached? %>
            <%= cl_image_tag list.photo.key, height: 40, width: 40, crop: :fill %>
          <% else %>
            <%= image_tag "logo.png", alt: "tadam", height: 40, width: 40 %>
          <% end %>
          <span><%= list.name %></span>
        <% end %>
      </li>
    <% end %>
  </ul>

  <hr />


  <div class="dropdown">
    <a href="#" class="dropdown-toggle text-white" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
      <img src="https://github.com/mdo.png" alt="profile" class="me-2">
      <strong>mdo</strong>
    </a>
    <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
      <li><a class="dropdown-item" href="#">New project...</a></li>
      <li><a class="dropdown-item" href="#">Settings</a></li>
      <li><a class="dropdown-item" href="#">Profile</a></li>
      <li><hr class="dropdown-divider"></li>
      <li><a class="dropdown-item" href="#">Sign out</a></li>
    </ul>
  </div>
</div>